## Writes content/test_vectors.json: sample states and the numbers the shared
## formulas must give. Both the Godot tests and the backend tests check them,
## so the two implementations cannot drift apart. Run headless:
##   godot --headless --path . res://tools/gen_test_vectors.tscn
extends Node

const OUT := "res://content/test_vectors.json"

const CASES := [
	{"name": "fresh", "gear": {}},
	{"name": "sword 3", "gear": {"sword": 3}},
	{"name": "early set", "gear": {"sword": 12, "chest": 4, "helmet": 1}},
	{"name": "legs and boots", "gear": {"sword": 40, "chest": 20, "helmet": 10, "legs": 6, "boots": 3}},
	{"name": "mid game", "gear": {"sword": 120, "chest": 80, "helmet": 60, "legs": 40, "boots": 30, "gloves": 20, "shoulders": 5}},
	{"name": "late game", "gear": {"sword": 500, "chest": 400, "helmet": 300, "legs": 250, "boots": 200, "gloves": 150, "shoulders": 100, "bracers": 60, "belt": 30, "cloak": 10}},
]

const COSTS := [
	["sword", 0, 1], ["sword", 0, 3], ["sword", 42, 3], ["chest", 0, 1], ["helmet", 7, 10],
	["legs", 0, 1], ["boots", 12, 25], ["gloves", 3, 2], ["cloak", 0, 1], ["cloak", 99, 1],
]


func _ready() -> void:
	var states: Array = []
	for c in CASES:
		var st := InitialState.make()
		for slot in c["gear"]:
			st["gear"][slot]["level"] = int(c["gear"][slot])
			st["gear"][slot]["unlocked"] = true
		states.append({
			"name": c["name"],
			"gear": c["gear"],
			"gold_per_metre": Selectors.gold_per_metre(st),
			"coin_value": Selectors.coin_value(st),
			"run_speed_mult": Selectors.run_speed_mult(st),
			"expected_gold_per_second": {"dark_forest": Selectors.expected_gold_per_second(st, "dark_forest")},
			"enemy_gold": {
				"vine_plant": Selectors.enemy_gold(st, Spawner.enemy_data("vine_plant")),
				"moss_golem": Selectors.enemy_gold(st, Spawner.enemy_data("moss_golem")),
				"giant_frog": Selectors.enemy_gold(st, Spawner.enemy_data("giant_frog")),
				"forest_spirit": Selectors.enemy_gold(st, Spawner.enemy_data("forest_spirit")),
			},
		})
	var costs: Array = []
	for c in COSTS:
		costs.append({"slot": c[0], "from_level": c[1], "count": c[2], "cost": Selectors.level_cost_sum(c[0], c[1], c[2])})
	var out := {
		"content_version": Content.load_json("res://content/meta.json")["content_version"],
		"note": "Generated by tools/gen_test_vectors.gd. Do not edit by hand.",
		"states": states,
		"level_costs": costs,
	}
	var f := FileAccess.open(OUT, FileAccess.WRITE)
	f.store_string(JSON.stringify(out, "  "))
	f.close()
	print("wrote ", OUT)
	get_tree().quit()
